name: Test and Lint
on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

jobs:
    test:
      name: Test
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Set up Go
          uses: actions/setup-go@v5
          with:
            go-version: 1.22
        - name: Set up gotestfmt
          uses: haveyoudebuggedit/gotestfmt-action@v2
          with:
            # Optional: pass GITHUB_TOKEN to avoid rate limiting.
            token: ${{ secrets.GITHUB_TOKEN }}
        - name: Run tests
          run: |
            set -euo pipefail
            go test -coverprofile cover.out -json -v ./... 2>&1 | tee /tmp/gotest.log | gotestfmt
        - name: Upload coverage reports to Codecov
          uses: codecov/codecov-action@v4
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
            slug: kalverra/adam-prism
            files: ./cover.out

    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                go-version: 1.22
            - name: golangci-lint
              uses: golangci/golangci-lint-action@v6
              with:
                version: latest
